### ISSUE TITLE
Используйте тестовые данные попроще

### ISSUE THREAD

**Issue by coursar** [sergey-lb/store-sales#1]
https://github.com/sergey-lb/store-sales/blob/e9ba7845ae5ef58c1047948e12ba84c68d511d85/app/lib.py#L4-L8

По этим данным сложно с первого взгляда понять, какой магазин лучше

**Comment by coursar** [comment]
Я бы не сказал, что шибко проще стало ))

Используйте 10, 1, 100 - гораздо же проще считать? На глаз не скажешь, что больше, 2 или 3

**Comment by sergey-lb** [comment]
Да, действительно )) Поправил.
